# Generated by Django 4.1.5 on 2023-03-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_b_18', '0002_remove_user_created_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('S', 'Student'), ('A', 'Advisor')], default='S', max_length=1),
        ),
    ]
