# Generated by Django 4.1.5 on 2023-03-29 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_b_18', '0004_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_nbr',
            field=models.CharField(default='16351', max_length=6),
        ),
        migrations.AddField(
            model_name='class',
            name='class_term',
            field=models.CharField(default='1228', max_length=4),
        ),
        migrations.AlterField(
            model_name='class',
            name='instructor',
            field=models.CharField(default='Aaron', max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(default='CS', max_length=6),
        ),
        migrations.AlterField(
            model_name='class',
            name='term',
            field=models.CharField(default='8', max_length=1),
        ),
        migrations.RemoveField(
            model_name='class',
            name='user',
        ),
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AddField(
            model_name='class',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
