# Generated by Django 4.1.5 on 2023-03-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_b_18', '0005_remove_class_check_full_class_class_nbr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='class',
            name='term',
        ),
        migrations.RemoveField(
            model_name='class',
            name='units',
        ),
        migrations.RemoveField(
            model_name='class',
            name='year',
        ),
    ]
