# Generated by Django 4.1.5 on 2023-03-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_b_18', '0006_remove_class_instructor_remove_class_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_nbr',
            field=models.IntegerField(default=16351),
        ),
    ]
