# Generated by Django 4.1.5 on 2023-03-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_b_18', '0007_alter_class_class_nbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='json_raw',
            field=models.JSONField(default={'class_nbr': 16351, 'class_term': '1228'}),
        ),
    ]
