# Generated by Django 4.1.5 on 2023-03-29 22:59

from django.db import migrations, models
import project_b_18.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_b_18', '0008_class_json_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='json_raw',
            field=models.JSONField(default=project_b_18.models.class_default),
        ),
    ]
