# Generated by Django 3.2.17 on 2023-04-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_b_18', '0010_auto_20230410_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schedule_term',
            field=models.CharField(default='1238', max_length=4),
        ),
    ]
